# Generated by Django 6.0.6 on 2026-08-23 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_initial"),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="ganancias_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="supplier",
            name="iibb_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="supplier",
            name="is_ganancias_exempt",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="supplier",
            name="is_iibb_exempt",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="supplier",
            name="iva_condition",
            field=models.CharField(
                choices=[
                    ("RI", "Responsable Inscripto"),
                    ("MONO", "Monotributo"),
                    ("EX", "Exento"),
                    ("NR", "No Responsable"),
                ],
                default="RI",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suppliers_thirdpartytaxprofiles",
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="tax_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="supplier",
            unique_together={("company", "name")},
        ),
        migrations.CreateModel(
            name="ThirdPartyTaxProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("tax_id", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "iva_condition",
                    models.CharField(
                        choices=[
                            ("RI", "Responsable Inscripto"),
                            ("MONO", "Monotributo"),
                            ("EX", "Exento"),
                            ("NR", "No Responsable"),
                        ],
                        default="RI",
                        max_length=10,
                    ),
                ),
                (
                    "iibb_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("is_iibb_exempt", models.BooleanField(default=False)),
                (
                    "ganancias_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("is_ganancias_exempt", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_tax_profiles",
                        to="company.company",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("company", "name")},
            },
        ),
        migrations.AlterField(
            model_name="supplier",
            name="tax_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="suppliers.thirdpartytaxprofile",
            ),
        ),
    ]
