# Generated by Django 6.0.6 on 2026-07-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_supplier_options_supplier_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
