# Generated by Django 6.0.6 on 2026-07-29 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0004_thirdpartytaxprofile_ganancias_percentage_and_more'),
        ('suppliers', '0003_supplier_tax_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='tax_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='fiscal.thirdpartytaxprofile'),
        ),
    ]
