# Generated by Django 6.1.1 on 2026-09-30 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0015_thirdpartytaxprofile_name_and_more'),
        ('suppliers', '0003_alter_supplier_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='tax_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='fiscal.thirdpartytaxprofile'),
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='ganancias_rate',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='iibb_rate',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='is_ganancias_exempt',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='is_iibb_exempt',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='iva_condition',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='tax_id',
        ),
        migrations.DeleteModel(
            name='ThirdPartyTaxProfile',
        ),
    ]
