from .afip_activity import AFIPActivityForm
from .company_tax_profile import CompanyTaxProfileForm
from .electronic_voucher_book import ElectronicVoucherBookForm
from .fiscal_invoice import FiscalInvoiceForm
from .fiscal_invoice_line import FiscalInvoiceLineForm
from .fiscal_product import FiscalProductForm
from .fiscal_service import FiscalServiceForm
from .thirdparty_tax_profile import ThirdPartyTaxProfileForm
