# Generated by Django 6.0.6 on 2026-08-29 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0006_alter_fiscalinvoice_options_and_more'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasetax',
            name='vat_type',
        ),
        migrations.AddField(
            model_name='purchasetax',
            name='tax',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_taxes', to='fiscal.tax'),
            preserve_default=False,
        ),
    ]
