# Generated by Django 6.0.6 on 2026-07-01 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('purchases', '0002_purchase_purchaseline_purchaseperception_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='purchaseline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='purchaseperception',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='purchaseretention',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='purchasetax',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='purchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='purchases.supplier'),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='expense_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseperception',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseperception',
            name='perception_type',
            field=models.CharField(choices=[('IIBB', 'IIBB'), ('IVA', 'IVA'), ('MUNI', 'Municipal')], max_length=10),
        ),
        migrations.AlterField(
            model_name='purchaseretention',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseretention',
            name='retention_type',
            field=models.CharField(choices=[('GAN', 'Ganancias'), ('IVA', 'IVA'), ('SUSS', 'SUSS')], max_length=10),
        ),
        migrations.AlterField(
            model_name='purchasetax',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchasetax',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchasetax',
            name='vat_type',
            field=models.CharField(choices=[('0', '0%'), ('105', '10.5%'), ('21', '21%'), ('27', '27%')], max_length=10),
        ),
    ]
