# Generated by Django 6.0.6 on 2026-08-29 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0006_alter_fiscalinvoice_options_and_more'),
        ('purchases', '0002_remove_purchasetax_vat_type_purchasetax_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasetax',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_taxes', to='fiscal.tax'),
        ),
    ]
