# Generated by Django 6.1.1 on 2026-09-23 19:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0009_alter_account_unique_together_and_more"),
        ("fiscal", "0013_alter_thirdpartytaxprofile_customer"),
        ("purchases", "0003_alter_purchasetax_tax"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseline",
            name="tax",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_lines",
                to="fiscal.tax",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseline",
            name="expense_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_lines",
                to="accounting.account",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseline",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("1.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="purchaseline",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
    ]
