# Generated by Django 6.0.6 on 2026-08-02 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_purchase_is_active'),
        ('suppliers', '0004_supplier_tax_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='suppliers.supplier'),
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
