# Generated by Django 6.1.1 on 2026-09-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "purchases",
            "0004_purchaseline_tax_alter_purchaseline_expense_account_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchaseperception",
            options={},
        ),
        migrations.AlterModelOptions(
            name="purchaseretention",
            options={},
        ),
        migrations.AlterModelOptions(
            name="purchasetax",
            options={},
        ),
        migrations.AddField(
            model_name="purchaseperception",
            name="jurisdiction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ARBA", "Buenos Aires (ARBA)"),
                    ("AGIP", "CABA (AGIP)"),
                    ("CÓRDOBA", "Córdoba"),
                    ("SANTA_FE", "Santa Fe"),
                    ("MENDOZA", "Mendoza"),
                    ("TUCUMÁN", "Tucumán"),
                    ("OTRA", "Otra Jurisdicción"),
                ],
                default="ARBA",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseperception",
            name="perception_type",
            field=models.CharField(
                choices=[
                    ("IIBB", "Ingresos Brutos"),
                    ("IVA", "IVA"),
                    ("MUNI", "Municipal"),
                    ("INTERNOS", "Impuestos Internos"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseretention",
            name="retention_type",
            field=models.CharField(
                choices=[
                    ("GAN", "Ganancias"),
                    ("IVA", "IVA"),
                    ("SUSS", "SUSS"),
                    ("IIBB", "IIBB"),
                ],
                max_length=10,
            ),
        ),
    ]
