# Generated by Django 6.1.1 on 2026-10-04 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_alter_account_unique_together_and_more'),
        ('fiscal', '0015_thirdpartytaxprofile_name_and_more'),
        ('purchases', '0005_alter_purchaseperception_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasetax',
            name='base_amount',
        ),
        migrations.AddField(
            model_name='purchaseperception',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='purchaseperception',
            name='notes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='purchasetax',
            name='taxable_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='purchaseperception',
            name='jurisdiction',
            field=models.CharField(blank=True, choices=[('ARBA', 'Buenos Aires (ARBA)'), ('AGIP', 'CABA (AGIP)'), ('CORDOBA', 'Córdoba'), ('SANTA_FE', 'Santa Fe'), ('MENDOZA', 'Mendoza'), ('TUCUMAN', 'Tucumán'), ('OTRA', 'Otra Jurisdicción')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchasetax',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='purchasetax',
            name='tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fiscal.tax'),
        ),
    ]
