MODULES = [
    {
        "code": "company",
        "name": "Company",
        "description": "General information",
        "url": "company:company_detail",
        "icon": "bi bi-building",
        "requires_company": True,
    },
    {
        "code": "activities",
        "name": "Activities",
        "description": "AFIP / Jurisdictions",
        "url": "company:company_activity_list",
        "icon": "bi bi-list-task",
        "requires_company": True,
    },
    {
        "code": "tax_profile",
        "name": "Tax Profile",
        "description": "IVA / IIBB / CUIT",
        "url": "company:company_tax_profile",
        "icon": "bi bi-gear",
        "requires_company": True,
    },
    {
        "code": "users",
        "name": "Users",
        "description": "Roles & permissions",
        "url": "company:company_user_list",
        "icon": "bi bi-people",
        "requires_company": True,
    },
    {
        "code": "accounting",
        "name": "Accounting",
        "description": "Journal, Ledger, Balances",
        "url": "accounting:journal_list",
        "icon": "bi bi-book",
        "requires_company": False,
    },
    {
        "code": "sales",
        "name": "Sales",
        "description": "Invoices & Customers",
        "url": "sales:sales_dashboard",
        "icon": "bi bi-receipt",
        "requires_company": False,
    },
    {
        "code": "purchases",
        "name": "Purchases",
        "description": "Suppliers & Expenses",
        "url": "purchases:purchase_list",
        "icon": "bi bi-cart",
        "requires_company": False,
    },
    {
        "code": "inventory",
        "name": "Inventory",
        "description": "Stock & Products",
        "url": "inventory:inventory_list",
        "icon": "bi bi-box",
        "requires_company": False,
    },
]
