# Generated by Django 6.0.6 on 2026-08-21 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_initial"),
        ("inventory", "0002_inventoryitem_company_inventorymovement_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="company.company"
            ),
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="company.company"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="company.company"
            ),
        ),
    ]
