# Generated by Django 6.0.6 on 2026-08-28 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_inventoryitem_company_and_more"),
        ("purchases", "0001_initial"),
        ("sales", "0002_saleitem_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorymovement",
            name="purchase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_movements",
                to="purchases.purchase",
            ),
        ),
        migrations.AddField(
            model_name="inventorymovement",
            name="sale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_movements",
                to="sales.sale",
            ),
        ),
    ]
