# Generated by Django 6.1.1 on 2026-09-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_inventorymovement_internal_tax"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorymovement",
            name="total_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="inventorymovement",
            name="unit_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
