# Generated by Django 6.0.6 on 2026-06-18 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyTaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afip_category', models.CharField(choices=[('RI', 'Responsable Inscripto'), ('MONO', 'Monotributo'), ('EX', 'Exento'), ('CF', 'Consumidor Final'), ('NR', 'No Responsable'), ('MT', 'Monotributo Social')], max_length=10)),
                ('vat_21', models.BooleanField(default=True)),
                ('vat_105', models.BooleanField(default=False)),
                ('vat_27', models.BooleanField(default=False)),
                ('vat_exempt', models.BooleanField(default=False)),
                ('vat_non_taxed', models.BooleanField(default=False)),
                ('iibb_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('iibb_exempt', models.BooleanField(default=False)),
                ('ganancias_agent', models.BooleanField(default=False)),
                ('perceptions_enabled', models.BooleanField(default=False)),
                ('retentions_enabled', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
