# Generated by Django 6.0.6 on 2026-08-19 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AFIPActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('description_long', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicVoucherBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_of_sale', models.IntegerField()),
                ('voucher_type', models.CharField(choices=[('FA', 'Factura A'), ('FB', 'Factura B'), ('FC', 'Factura C'), ('NCA', 'Nota de Crédito A'), ('NCB', 'Nota de Crédito B'), ('NCC', 'Nota de Crédito C'), ('NDA', 'Nota de Débito A'), ('NDB', 'Nota de Débito B'), ('NDC', 'Nota de Débito C')], max_length=4)),
                ('current_number', models.IntegerField(default=1)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FiscalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=21, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='FiscalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=21, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdPartyTaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afip_category', models.CharField(choices=[('RI', 'Responsable Inscripto'), ('MONO', 'Monotributo'), ('EX', 'Exento'), ('CF', 'Consumidor Final'), ('NR', 'No Responsable'), ('MT', 'Monotributo Social')], max_length=10)),
                ('vat_21', models.BooleanField(default=True)),
                ('vat_105', models.BooleanField(default=False)),
                ('vat_27', models.BooleanField(default=False)),
                ('vat_exempt', models.BooleanField(default=False)),
                ('vat_non_taxed', models.BooleanField(default=False)),
                ('ganancias_status', models.CharField(choices=[('INSCRIPTO', 'Inscripto'), ('EXENTO', 'Exento'), ('NO_CORRESPONDE', 'No corresponde (Monotributista)')], default='NO_CORRESPONDE', max_length=20)),
                ('iibb_status', models.CharField(choices=[('INSCRIPTO', 'Inscripto'), ('EXENTO', 'Exento'), ('NO_CORRESPONDE', 'No corresponde')], default='NO_CORRESPONDE', max_length=20)),
                ('uses_perceptions', models.BooleanField(default=False)),
                ('uses_retentions', models.BooleanField(default=False)),
                ('iibb_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('iva_perception_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('ganancias_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('suss_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_21', models.BooleanField(default=True)),
                ('vat_105', models.BooleanField(default=False)),
                ('vat_27', models.BooleanField(default=False)),
                ('vat_exempt', models.BooleanField(default=False)),
                ('vat_non_taxed', models.BooleanField(default=False)),
                ('iibb_status', models.CharField(choices=[('LOCAL', 'Local'), ('MULTILATERAL', 'Multilateral'), ('EXEMPT', 'Exempt')], default='LOCAL', max_length=20)),
                ('ganancias_status', models.CharField(choices=[('INSCRIPTO', 'Inscripto'), ('NO_INSCRIPTO', 'No Inscripto'), ('EXENTO', 'Exento')], default='INSCRIPTO', max_length=20)),
                ('uses_perceptions', models.BooleanField(default=False)),
                ('uses_retentions', models.BooleanField(default=False)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='FiscalInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(choices=[('A', 'Factura A'), ('B', 'Factura B'), ('C', 'Factura C'), ('NC', 'Nota de Crédito'), ('ND', 'Nota de Débito')], default='B', max_length=5)),
                ('point_of_sale', models.IntegerField(default=1)),
                ('voucher_number', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('exempt_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('non_taxed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cae', models.CharField(blank=True, max_length=20, null=True)),
                ('cae_expiration', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_invoices', to='company.company')),
            ],
        ),
    ]
