# Generated by Django 6.0.6 on 2026-06-19 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyTaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afip_category', models.CharField(choices=[('RI', 'Responsable Inscripto'), ('MONO', 'Monotributo'), ('EX', 'Exento'), ('CF', 'Consumidor Final'), ('NR', 'No Responsable'), ('MT', 'Monotributo Social')], max_length=10)),
                ('vat_21', models.BooleanField(default=True)),
                ('vat_105', models.BooleanField(default=False)),
                ('vat_27', models.BooleanField(default=False)),
                ('vat_exempt', models.BooleanField(default=False)),
                ('vat_non_taxed', models.BooleanField(default=False)),
                ('ganancias_status', models.CharField(choices=[('INSCRIPTO', 'Inscripto'), ('EXENTO', 'Exento'), ('NO_CORRESPONDE', 'No corresponde (Monotributista)')], default='NO_CORRESPONDE', max_length=20)),
                ('iibb_status', models.CharField(choices=[('INSCRIPTO', 'Inscripto'), ('EXENTO', 'Exento'), ('NO_CORRESPONDE', 'No corresponde')], default='NO_CORRESPONDE', max_length=20)),
                ('uses_perceptions', models.BooleanField(default=False)),
                ('uses_retentions', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
