# Generated by Django 6.0.6 on 2026-06-26 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_companyactivity_code_and_more'),
        ('fiscal', '0002_afipactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_21', models.BooleanField(default=True)),
                ('vat_105', models.BooleanField(default=False)),
                ('vat_27', models.BooleanField(default=False)),
                ('vat_exempt', models.BooleanField(default=False)),
                ('vat_non_taxed', models.BooleanField(default=False)),
                ('iibb_status', models.CharField(choices=[('LOCAL', 'Local'), ('MULTILATERAL', 'Multilateral'), ('EXEMPT', 'Exempt')], default='LOCAL', max_length=20)),
                ('ganancias_status', models.CharField(choices=[('INSCRIPTO', 'Inscripto'), ('NO_INSCRIPTO', 'No Inscripto'), ('EXENTO', 'Exento')], default='INSCRIPTO', max_length=20)),
                ('uses_perceptions', models.BooleanField(default=False)),
                ('uses_retentions', models.BooleanField(default=False)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
