# Generated by Django 6.0.6 on 2026-08-23 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_initial"),
        ("fiscal", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fiscal_thirdpartytaxprofiles",
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="thirdpartytaxprofile",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fiscal_tax_profiles",
                to="company.company",
            ),
        ),
    ]
