# Generated by Django 6.0.6 on 2026-07-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0003_companyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdpartytaxprofile',
            name='ganancias_percentage',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='thirdpartytaxprofile',
            name='iibb_percentage',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='thirdpartytaxprofile',
            name='iva_perception_percentage',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='thirdpartytaxprofile',
            name='suss_percentage',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
    ]
