# Generated by Django 6.0.6 on 2026-08-28 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_initial"),
        ("fiscal", "0003_alter_companyprofile_company_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("is_vat", models.BooleanField(default=False)),
                ("is_exempt", models.BooleanField(default=False)),
                ("is_non_taxed", models.BooleanField(default=False)),
                ("is_perception", models.BooleanField(default=False)),
                ("is_retention", models.BooleanField(default=False)),
                ("is_internal_tax", models.BooleanField(default=False)),
                ("afip_code", models.IntegerField(default=0)),
                (
                    "account_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.AlterModelOptions(
            name="electronicvoucherbook",
            options={"ordering": ["company", "point_of_sale", "voucher_type"]},
        ),
        migrations.AddField(
            model_name="electronicvoucherbook",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voucher_books",
                to="company.company",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="electronicvoucherbook",
            unique_together={("company", "point_of_sale", "voucher_type")},
        ),
        migrations.CreateModel(
            name="FiscalInvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.company",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="fiscal.fiscalinvoice",
                    ),
                ),
                (
                    "tax",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="fiscal.tax"
                    ),
                ),
            ],
            options={
                "ordering": ["invoice_id", "id"],
            },
        ),
    ]
