# Generated by Django 6.0.6 on 2026-08-02 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0004_thirdpartytaxprofile_ganancias_percentage_and_more'),
        ('sales', '0003_alter_customer_options_customer_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdpartytaxprofile',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_tax_profile', to='sales.customer'),
        ),
    ]
