# Generated by Django 6.0.6 on 2026-08-17 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_companyactivity_code_and_more'),
        ('fiscal', '0005_thirdpartytaxprofile_customer'),
        ('sales', '0004_alter_customer_tax_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicVoucherBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_of_sale', models.IntegerField()),
                ('voucher_type', models.CharField(choices=[('FA', 'Factura A'), ('FB', 'Factura B'), ('FC', 'Factura C'), ('NCA', 'Nota de Crédito A'), ('NCB', 'Nota de Crédito B'), ('NCC', 'Nota de Crédito C'), ('NDA', 'Nota de Débito A'), ('NDB', 'Nota de Débito B'), ('NDC', 'Nota de Débito C')], max_length=4)),
                ('current_number', models.IntegerField(default=1)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FiscalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=21, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='FiscalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=21, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='FiscalInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cae', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.customer')),
                ('voucher_book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fiscal.electronicvoucherbook')),
            ],
        ),
        migrations.CreateModel(
            name='FiscalInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=21, max_digits=4)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='fiscal.fiscalinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='FiscalSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fiscal.fiscalinvoice')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.sale')),
                ('voucher_book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fiscal.electronicvoucherbook')),
            ],
        ),
    ]
