# Generated by Django 6.0.6 on 2026-08-29 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
        ('fiscal', '0005_fiscalinvoice_legacy_rename_and_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiscalinvoice',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AddField(
            model_name='fiscalinvoice',
            name='cae_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiscalinvoice',
            name='customer_name',
            field=models.CharField(default='Factura', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiscalinvoice',
            name='customer_tax_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fiscalinvoice',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fiscalinvoice',
            name='vat_105',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='fiscalinvoice',
            name='vat_21',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='fiscalinvoice',
            name='vat_27',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='fiscalinvoice',
            name='vat_exempt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='fiscalinvoice',
            name='vat_non_taxed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='fiscalinvoice',
            name='voucher_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='fiscal.electronicvoucherbook'),
        ),
        migrations.AddField(
            model_name='fiscalproduct',
            name='tax',
            field=models.ForeignKey(blank=True, help_text='Impuesto fiscal centralizado. Si se deja vacío, se usa vat_rate como compatibilidad.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_products', to='fiscal.tax'),
        ),
        migrations.AddField(
            model_name='fiscalservice',
            name='tax',
            field=models.ForeignKey(blank=True, help_text='Impuesto fiscal centralizado. Si se deja vacío, se usa vat_rate como compatibilidad.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_services', to='fiscal.tax'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_company_profiles', to='company.company'),
        ),
        migrations.AlterField(
            model_name='fiscalinvoice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_invoices', to='company.company'),
        ),
        migrations.AlterField(
            model_name='fiscalinvoice',
            name='date',
            field=models.DateField(),
        ),
    ]
