# Generated by Django 6.1.1 on 2026-09-03 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0006_alter_fiscalinvoice_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fiscalinvoice",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="fiscalinvoice",
            name="point_of_sale",
        ),
        migrations.RemoveField(
            model_name="fiscalinvoice",
            name="sale",
        ),
        migrations.RemoveField(
            model_name="fiscalinvoice",
            name="voucher_type",
        ),
        migrations.AlterField(
            model_name="fiscalinvoice",
            name="voucher_book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="fiscal.electronicvoucherbook",
            ),
        ),
    ]
