# Generated by Django 6.1.1 on 2026-09-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_initial"),
        ("fiscal", "0008_seed_default_vat_taxes"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="companyprofile",
            constraint=models.UniqueConstraint(
                fields=("company",), name="unique_tax_profile_per_company"
            ),
        ),
    ]
