# Generated by Django 6.1.1 on 2026-09-12 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0009_companyprofile_unique_tax_profile_per_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiscalinvoice",
            name="point_of_sale",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="fiscalinvoice",
            name="number",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="fiscalinvoice",
            name="voucher_book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="fiscal.electronicvoucherbook",
            ),
        ),
    ]
