# Generated by Django 6.1.1 on 2026-09-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0010_fiscalinvoice_point_of_sale_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fiscalinvoice",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
