# Generated by Django 6.1.1 on 2026-09-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0011_alter_fiscalinvoice_date"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="companyprofile",
            name="unique_tax_profile_per_company",
        ),
        migrations.AddConstraint(
            model_name="companyprofile",
            constraint=models.UniqueConstraint(
                fields=("company",), name="fiscal_unique_tax_profile_per_company"
            ),
        ),
    ]
