# Generated by Django 6.1.1 on 2026-09-23 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_customer_city_customer_country_and_more"),
        (
            "fiscal",
            "0012_remove_companyprofile_unique_tax_profile_per_company_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="thirdpartytaxprofile",
            name="customer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tax_profile",
                to="customers.customer",
            ),
        ),
    ]
