# Generated by Django 6.1.1 on 2026-09-25 21:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0013_alter_thirdpartytaxprofile_customer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="thirdpartytaxprofile",
            options={
                "verbose_name": "Perfil Fiscal de Tercero",
                "verbose_name_plural": "Perfiles Fiscales de Terceros",
            },
        ),
        migrations.RenameField(
            model_name="thirdpartytaxprofile",
            old_name="uses_perceptions",
            new_name="is_ganancias_exempt",
        ),
        migrations.RenameField(
            model_name="thirdpartytaxprofile",
            old_name="uses_retentions",
            new_name="is_iibb_exempt",
        ),
        migrations.RemoveField(
            model_name="thirdpartytaxprofile",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="thirdpartytaxprofile",
            name="ganancias_percentage",
        ),
        migrations.RemoveField(
            model_name="thirdpartytaxprofile",
            name="iibb_percentage",
        ),
        migrations.RemoveField(
            model_name="thirdpartytaxprofile",
            name="iva_perception_percentage",
        ),
        migrations.RemoveField(
            model_name="thirdpartytaxprofile",
            name="suss_percentage",
        ),
        migrations.AddField(
            model_name="thirdpartytaxprofile",
            name="ganancias_regime",
            field=models.CharField(
                blank=True,
                help_text="Código/Concepto de régimen RG 830 (ej. Honorarios, Alquileres, Bienes).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="thirdpartytaxprofile",
            name="ganancias_retention_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                help_text="Alícuota fija o especial de retención de Ganancias.",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="thirdpartytaxprofile",
            name="iibb_perception_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                help_text="Alícuota de percepción IIBB que el proveedor nos recarga en facturas (ej. 3.5%).",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="thirdpartytaxprofile",
            name="iibb_retention_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                help_text="Alícuota de retención de IIBB a aplicarle según padrón.",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="thirdpartytaxprofile",
            name="is_iibb_perception_agent",
            field=models.BooleanField(
                default=False,
                help_text="Marcar si el proveedor es Agente de Percepción de IIBB (ARBA/AGIP).",
            ),
        ),
        migrations.AddField(
            model_name="thirdpartytaxprofile",
            name="is_iva_perception_agent",
            field=models.BooleanField(
                default=False,
                help_text="Marcar si el proveedor nos aplica percepciones de IVA.",
            ),
        ),
        migrations.AddField(
            model_name="thirdpartytaxprofile",
            name="iva_perception_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                help_text="Alícuota de percepción IVA (ej. 3.0%).",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="thirdpartytaxprofile",
            name="iva_retention_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                help_text="Alícuota de retención de IVA (ej. 50% o 80% de la alícuota de IVA).",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="thirdpartytaxprofile",
            name="perception_jurisdiction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ARBA", "Buenos Aires (ARBA)"),
                    ("AGIP", "CABA (AGIP)"),
                    ("CORDOBA", "Córdoba"),
                    ("SANTA_FE", "Santa Fe"),
                    ("MENDOZA", "Mendoza"),
                    ("TUCUMAN", "Tucumán"),
                    ("OTRA", "Otra Jurisdicción"),
                ],
                default="ARBA",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="thirdpartytaxprofile",
            name="suss_retention_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                help_text="Alícuota de retención de SUSS.",
                max_digits=6,
            ),
        ),
        migrations.AlterField(
            model_name="thirdpartytaxprofile",
            name="afip_category",
            field=models.CharField(
                choices=[
                    ("RI", "Responsable Inscripto"),
                    ("MONO", "Monotributo"),
                    ("EX", "Exento"),
                    ("CF", "Consumidor Final"),
                    ("NR", "No Responsable"),
                    ("MT", "Monotributo Social"),
                ],
                default="RI",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="thirdpartytaxprofile",
            name="ganancias_status",
            field=models.CharField(
                choices=[
                    ("INSCRIPTO", "Inscripto (Sujeto a Retención RG 830)"),
                    ("EXENTO", "Exento (Certificado de Exención)"),
                    ("NO_CORRESPONDE", "No Corresponde (Monotributista / Individuo)"),
                ],
                default="INSCRIPTO",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="thirdpartytaxprofile",
            name="iibb_status",
            field=models.CharField(
                choices=[
                    ("LOCAL", "Inscripto Local"),
                    ("MULTILATERAL", "Convenio Multilateral"),
                    ("EXENTO", "Exento"),
                    ("NO_INSCRIPTO", "No Inscripto"),
                ],
                default="LOCAL",
                max_length=20,
            ),
        ),
    ]
