# Generated by Django 6.1.1 on 2026-09-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0014_alter_thirdpartytaxprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdpartytaxprofile',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='thirdpartytaxprofile',
            name='tax_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
