"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""
from pathlib import Path
import os

# =============================================================================
# PATHS
# =============================================================================

BASE_DIR = Path(__file__).resolve().parent.parent

# =============================================================================
# SECURITY
# =============================================================================

SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-change-me"
)

DEBUG = os.environ.get(
    "DJANGO_DEBUG",
    "1"
) == "1"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        "DJANGO_ALLOWED_HOSTS",
        "localhost,127.0.0.1"
    ).split(",")
    if host.strip()
]

# =============================================================================
# APPLICATIONS
# =============================================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # ERP Apps
    "core.apps.CoreConfig",
    "company.apps.CompanyConfig",
    "accounting.apps.AccountingConfig",
    "sales.apps.SalesConfig",
    "purchases.apps.PurchasesConfig",
    "inventory.apps.InventoryConfig",
    "reports.apps.ReportsConfig",
    "fiscal.apps.FiscalConfig",
    "customers.apps.CustomersConfig",
    "suppliers.apps.SuppliersConfig",
    "products.apps.ProductsConfig",
]

# =============================================================================
# MIDDLEWARE
# =============================================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    # ERP
    "company.middleware.active_company.ActiveCompanyMiddleware",
    "company.middleware.role_permissions.RolePermissionMiddleware",
]

handler403 = "core.views.errors.error_403"

# =============================================================================
# URLS
# =============================================================================

ROOT_URLCONF = "config.urls"

WSGI_APPLICATION = "config.wsgi.application"

# =============================================================================
# TEMPLATES
# =============================================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates"
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.active_company",
            ],
        },
    },
]

# =============================================================================
# DATABASE
# =============================================================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.environ.get(
            "DB_NAME",
            "contabilidad_ar2"
        ),
        "USER": os.environ.get(
            "DB_USER",
            "django"
        ),
        "PASSWORD": os.environ.get(
            "DB_PASSWORD",
            "django123"
        ),
        "HOST": os.environ.get(
            "DB_HOST",
            "localhost"
        ),
        "PORT": os.environ.get(
            "DB_PORT",
            "3306"
        ),
        "CONN_MAX_AGE": 300,
        "OPTIONS": {
            "charset": "utf8mb4",
        },
    }
}

# =============================================================================
# AUTHENTICATION
# =============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"
    },
]

LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/accounts/login/"

# =============================================================================
# INTERNATIONALIZATION
# =============================================================================

LANGUAGE_CODE = "es-ar"

TIME_ZONE = "America/Argentina/Buenos_Aires"

USE_I18N = True

USE_TZ = True

# =============================================================================
# STATIC FILES
# =============================================================================

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "core" / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

# =============================================================================
# MEDIA FILES
# =============================================================================

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"

# =============================================================================
# DEFAULT PK
# =============================================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# =============================================================================
# SESSIONS
# =============================================================================

SESSION_EXPIRE_AT_BROWSER_CLOSE = False

SESSION_COOKIE_AGE = 60 * 60 * 24

# =============================================================================
# SECURITY HEADERS
# =============================================================================

X_FRAME_OPTIONS = "DENY"

SESSION_COOKIE_HTTPONLY = True

SECURE_CONTENT_TYPE_NOSNIFF = True

# =============================================================================
# LOGGING
# =============================================================================

LOG_DIR = BASE_DIR / "logs"

os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": (
                "%(asctime)s "
                "%(levelname)s "
                "%(name)s "
                "%(message)s"
            )
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "class": "logging.FileHandler",
            "filename": str(LOG_DIR / "erp_debug.log"),
            "formatter": "simple",
            "encoding": "utf-8",
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": "DEBUG" if DEBUG else "INFO",
    },
}

# =============================================================================
# AFIP
# =============================================================================

AFIP_MODE = os.environ.get(
    "AFIP_MODE",
    "testing"
).lower()

AFIP_WSFE_TEST_URL = (
    "https://wswhomo.afip.gov.ar/wsfev1/service.asmx"
)

AFIP_WSFE_PROD_URL = (
    "https://servicios1.afip.gov.ar/wsfev1/service.asmx"
)

AFIP_WSFE_URL = (
    AFIP_WSFE_TEST_URL
    if AFIP_MODE == "testing"
    else AFIP_WSFE_PROD_URL
)

AFIP_CERT = os.environ.get(
    "AFIP_CERT",
    str(BASE_DIR / "certs" / "cert.pem")
)

AFIP_KEY = os.environ.get(
    "AFIP_KEY",
    str(BASE_DIR / "certs" / "private.key")
)