# Generated by Django 6.1.1 on 2026-09-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_alter_customer_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="ganancias_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="customer",
            name="iibb_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_ganancias_exempt",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_iibb_exempt",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="iva_condition",
            field=models.CharField(
                choices=[
                    ("RI", "Responsable Inscripto"),
                    ("MONO", "Monotributo"),
                    ("EX", "Exento"),
                    ("CF", "Consumidor Final"),
                    ("NR", "No Responsable"),
                ],
                default="CF",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="tax_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
