# Generated by Django 6.1.1 on 2026-09-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_customer_ganancias_rate_customer_iibb_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="country",
            field=models.CharField(
                blank=True, default="Argentina", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="customer_type",
            field=models.CharField(
                choices=[("individual", "Individual"), ("company", "Company")],
                default="company",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="province",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
