# Generated by Django 6.0.6 on 2026-08-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('tax_id', models.CharField(max_length=20, unique=True)),
                ('afip_category', models.CharField(choices=[('RI', 'Responsable Inscripto'), ('MONO', 'Monotributo'), ('EX', 'Exento'), ('PYME', 'PyME'), ('GC', 'Gran Contribuyente'), ('PH', 'Persona Humana')], max_length=10)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Argentina', max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('accounting_start_date', models.DateField(blank=True, help_text='Date when accounting starts in this system', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('jurisdiction', models.CharField(blank=True, help_text='Optional: CABA, BsAs, Córdoba, etc.', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_21', models.BooleanField(default=True)),
                ('vat_105', models.BooleanField(default=False)),
                ('vat_27', models.BooleanField(default=False)),
                ('vat_exempt', models.BooleanField(default=False)),
                ('vat_non_taxed', models.BooleanField(default=False)),
                ('iibb_status', models.CharField(choices=[('INSCRIPTO', 'Inscripto'), ('EXENTO', 'Exento'), ('NO_CORRESPONDE', 'No corresponde')], default='NO_CORRESPONDE', max_length=20)),
                ('ganancias_status', models.CharField(choices=[('INSCRIPTO', 'Inscripto'), ('EXENTO', 'Exento'), ('NO_CORRESPONDE', 'No corresponde (Monotributista)')], default='NO_CORRESPONDE', max_length=20)),
                ('uses_perceptions', models.BooleanField(default=False)),
                ('uses_retentions', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ACCOUNTANT', 'Accountant'), ('DATAENTRY', 'Data Entry'), ('AUDITOR', 'Auditor'), ('VIEWER', 'Viewer')], max_length=20)),
                ('can_view_accounting', models.BooleanField(default=True)),
                ('can_edit_accounting', models.BooleanField(default=False)),
                ('can_view_fiscal', models.BooleanField(default=True)),
                ('can_edit_fiscal', models.BooleanField(default=False)),
                ('can_view_documents', models.BooleanField(default=True)),
                ('can_edit_documents', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
