# Generated by Django 6.0.6 on 2026-06-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='ganancias_agent',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='iibb_registered',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='ganancias_status',
            field=models.CharField(choices=[('INSCRIPTO', 'Inscripto'), ('EXENTO', 'Exento'), ('NO_CORRESPONDE', 'No corresponde (Monotributista)')], default='NO_CORRESPONDE', max_length=20),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='iibb_status',
            field=models.CharField(choices=[('INSCRIPTO', 'Inscripto'), ('EXENTO', 'Exento'), ('NO_CORRESPONDE', 'No corresponde')], default='NO_CORRESPONDE', max_length=20),
        ),
    ]
