# Generated by Django 6.1.1 on 2026-09-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyuser",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
