# Generated by Django 6.0.6 on 2026-06-21 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_companyprofile_ganancias_agent_and_more'),
        ('fiscal', '0002_afipactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyactivity',
            name='code',
        ),
        migrations.RemoveField(
            model_name='companyactivity',
            name='description',
        ),
        migrations.AddField(
            model_name='companyactivity',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_activities', to='fiscal.afipactivity'),
        ),
    ]
