# Generated by Django 6.1.1 on 2026-09-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_companyuser_is_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="ganancias_status",
            field=models.CharField(
                choices=[
                    ("INSCRIPTO", "Inscripto"),
                    ("NO_INSCRIPTO", "No Inscripto"),
                    ("EXENTO", "Exento"),
                ],
                default="INSCRIPTO",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="iibb_status",
            field=models.CharField(
                choices=[
                    ("LOCAL", "Local"),
                    ("MULTILATERAL", "Multilateral"),
                    ("EXEMPT", "Exempt"),
                ],
                default="LOCAL",
                max_length=20,
            ),
        ),
    ]
