# Generated by Django 6.1.1 on 2026-09-16 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0004_alter_journalentry_created_by"),
        ("purchases", "0003_alter_purchasetax_tax"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="purchase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="journal_entries",
                to="purchases.purchase",
            ),
        ),
    ]
