# Generated by Django 6.1.1 on 2026-09-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0006_accountingsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="code",
            field=models.CharField(max_length=40),
        ),
    ]
