# Generated by Django 6.1.1 on 2026-09-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0008_journalentry_idempotency_constraints"),
        ("company", "0004_alter_companyprofile_ganancias_status_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="account",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("company", "code"), name="unique_account_code_per_company"
            ),
        ),
    ]
