# Generated by Django 6.0.6 on 2026-08-23 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_company"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sale_items",
                to="products.product",
            ),
        ),
    ]
