# Generated by Django 6.0.6 on 2026-08-29 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0006_alter_fiscalinvoice_options_and_more'),
        ('sales', '0002_saleitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='tax_category',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='fiscal.tax'),
        ),
    ]
