# Generated by Django 6.1.1 on 2026-09-07 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_remove_saleitem_tax_category_saleitem_tax"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sale",
            options={"ordering": ["-date", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="saleitem",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="sale",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
