# Generated by Django 6.0.6 on 2026-08-02 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0005_thirdpartytaxprofile_customer'),
        ('sales', '0003_alter_customer_options_customer_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tax_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to='fiscal.thirdpartytaxprofile'),
        ),
    ]
