# Generated by Django 6.1.1 on 2026-09-21 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_customer_city_customer_country_and_more"),
        ("sales", "0005_sync_general_customers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales",
                to="customers.customer",
            ),
        ),
    ]
