# Generated by Django 6.1.1 on 2026-09-23 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0007_sale_status_alter_sale_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
