# Generated by Django 6.1.1 on 2026-09-30 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
