# Generated by Django 6.0.6 on 2026-08-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('type', models.CharField(choices=[('PRODUCT', 'Product'), ('SERVICE', 'Service')], default='PRODUCT', max_length=10)),
            ],
        ),
    ]
