# Generated by Django 6.0.6 on 2026-08-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('PRODUCT', 'Product'), ('SERVICE', 'Service')], default='PRODUCT', max_length=10),
        ),
    ]
