# Generated by Django 6.0.6 on 2026-08-21 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_initial"),
        ("company", "0002_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.company",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="detail",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="income_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Cuenta contable de ingreso (Ventas de Mercaderías o Servicios)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
