# Generated by Django 6.0.6 on 2026-08-29 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0006_alter_fiscalinvoice_options_and_more'),
        ('products', '0003_alter_product_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.ForeignKey(blank=True, help_text='Impuesto AFIP asociado al producto', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='fiscal.tax'),
        ),
    ]
