# Generated by Django 6.1.1 on 2026-09-07 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_accountmovement"),
        ("fiscal", "0008_seed_default_vat_taxes"),
        ("products", "0004_product_tax"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="product",
            name="income_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounting.account",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tax",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="fiscal.tax",
            ),
        ),
    ]
