# Generated by Django 6.1.1 on 2026-09-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0008_journalentry_idempotency_constraints"),
        ("company", "0004_alter_companyprofile_ganancias_status_and_more"),
        (
            "fiscal",
            "0012_remove_companyprofile_unique_tax_profile_per_company_and_more",
        ),
        (
            "products",
            "0005_alter_product_options_alter_product_income_account_and_more",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("company", "sku"), name="unique_product_sku_per_company"
            ),
        ),
    ]
